### ISSUE TITLE
CTSgetR() does not return the scores

### ISSUE THREAD

**Issue by sneumann** [dgrapov/CTSgetR#3]
Hi, when converting from names to PubChem, the web interface 
has scores which are reasonably good to assess the ID confidence.
It would be cool to have that accessible from R as well.
```
5-Methyltetrahydrofolic acid 	
444412   -> 1.0
146      -> 0.1921
9825434  -> 0.3353
439234   -> 0.0703
```

**Comment by dgrapov** [comment]
This can be done only from 'Common Name' to 'InchiKey' e.g. using `name_to_inchikey()`.
