### ISSUE TITLE
Is there an option to convert inchikey values to smiles ?

### ISSUE THREAD

**Issue by TalWac** [dgrapov/CTSgetR#4]
Dear developers,

I want to ask if there's an option to convert Inchikey values to **Smiles** ?

Best regards,

Tal

**Comment by dgrapov** [comment]
It does not look like CTS supports smiles as a `to` translation option. 

```r
library(CTSgetR)
want<-'sm'
possible_to<-unlist(valid_to())
possible_to[grepl(want,possible_to,ignore.case=TRUE)]
```

You can try one of these options:
webchem::get_csid  #https://docs.ropensci.org/webchem/reference/get_csid.html
rcdkTools::inchi2smiles   #https://rdrr.io/github/bachi55/rcdkTools/man/inchi2smiles.html - requires installing open babel

**Comment by dgrapov** [comment]
This feature is not supported by CTS. You can try [CIRgetR](https://github.com/dgrapov/CIRgetR/). Note its been a while since I tested it :)
